// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    donation
    (
        init => init
        initMinting => init_minting
        donate => donate
        acceptTierNft => accept_tier_nft
        mintTierNfts => mint_tier_nfts
        sendEgldsToOwner => send_eglds_to_owner
        setMinDonation => set_min_donation
        setMaxDonationDestinationId => set_max_donation_destination_id
        setTierThresholds => set_tier_thresholds
        setDonationState => set_donation_state
        setMintingState => set_minting_state
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
